import { HotelImage } from "../constants/index";

export const HOTELS = [
  {
    id: 1,
    name: "New Eastern Comfort Hotel and Garden Resort LTD",
    address: "134 Aba Road, 440236 Umuahia, Nigeria",
    lat: 5.2205,
    lng: 7.523659,
    rating: "★★★",
    distance: "1.9 mi",
    time: "20 min",
    bookBefore: "Dec 23, 2025",
    rate: 65,
    images: HotelImage.slice(7, 9).map((img) => img.src),
  },

  {
    id: 2,
    name: "Stella Luxury Apartment",
    address:
      "C25, AGBAZUERE STREET WORLD BANK HOUSING ESTATE, Ohokobe Ndume, Nigeria",
    lat: 5.513341,
    lng: 7.523659,
    rating: "★★★★",
    distance: "2.0 mi",
    time: "5 min",
    bookBefore: "Dec 26, 2025",
    rate: 50,
    images: HotelImage.slice(17, 19).map((img) => img.src),
  },
  {
    id: 3,
    name: "AOSL Homes",
    address: "Elizabeth Edward Compound, Umuahia, 440236 Unuahia",
    lat: 5.513341,
    lng: 7.523659,
    rating: "★★★",
    distance: "2.5 mi",
    time: "6 min",
    bookBefore: "Dec 23, 2025",
    rate: 25,
    images: HotelImage.slice(0, 2).map((img) => img.src),
  },
  {
    id: 4,
    name: "Divine Villa and Resort Guest House",
    address:
      "PLOT 35 UMUEZEUKWU ROAD BEHIND IKWUEKE CENTRAL SCHOOL, OBORO, IKWUANO LGA, ABIA STATE",
    lat: 5.526996,
    lng: 7.523659,
    rating: "★★★",
    distance: "1.5 mi",
    time: "3 min",
    bookBefore: "Dec 27, 2025",
    rate: 90,
    images: HotelImage.slice(4, 6).map((img) => img.src),
  },
  {
    id: 5,
    name: "Luxury short-let apartments",
    address:
      "Hon.Ejike Obike Rd. By Asonye Close off Divinity Rd Old Umuahia Abia State",
    lat: 5.607625,
    lng: 7.516908,
    rating: "★★★★",
    distance: "3.0 mi",
    time: "7 min",
    bookBefore: "Dec 19, 2025",
    rate: 100,
    images: HotelImage.slice(14, 16).map((img) => img.src),
  },
  {
    id: 6,
    name: "Cozy & Serene Sanctuary-The Paletinos Homes",
    address:
      "Behind Upstair Line New Timber Industrial Market Umuahia, 440103 Umuahia",
    lat: 5.513233,
    lng: 7.533577,
    rating: "★★★★",
    distance: "2.2 mi",
    time: "5 min",
    bookBefore: "Dec 24, 2025",
    rate: 55,
    images: HotelImage.slice(19, 21).map((img) => img.src),
  },
];
